### ISSUE TITLE
1.38 patch by Arma3

### ISSUE THREAD

**Issue by sandycaine** [ChristopheTdn/FSF-LAUNCHER-ARMA3#3]
The launcher in offline mode throws more Arma3. You must launch it from the exe of the game, then quit the game and then relaunch with the launcher.Thank you.Sorry for my terrible English

**Comment by ChristopheTdn** [comment]
the FSF Launcher is no more developped.

but you can follow the developpement with the the Gos Launcher project. : https://github.com/ChristopheTdn/GOS-LAUNCHER-ARMA3

just changing name after conflict with FSF clan leader
