### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by JPad90** [ChristopheTdn/FSF-LAUNCHER-ARMA3#4]
In your current Repo, my Studio missing the DIAL_SynchroMission.cs and DIAL_SynchroMission.resx
Ppls cann you fix it on your GitHub Page.

with best regards

JPad

**Comment by JPad90** [comment]
Also is missing theGestFile.cs, Projet1.ico and splascreen.png

**Comment by JPad90** [comment]
Also is missing theGestFile.cs, Projet1.ico and splascreen.png

**Comment by ChristopheTdn** [comment]
the FSF Launcher is no more developped.

but you can follow the developpement with the the Gos Launcher project. : https://github.com/ChristopheTdn/GOS-LAUNCHER-ARMA3

just changing name after conflict with FSF clan leader
